name: Build and deploy Node.js app to Azure Web App - backend-stay-easy

on:
  push:
    branches: ["main"]
    paths:
      - 'BackEnd/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./BackEnd

      - name: Build the app
        run: npm run build --if-present
        working-directory: ./BackEnd

      - name: Run tests
        run: npm run test --if-present
        working-directory: ./BackEnd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./BackEnd

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32FEC9CB2DE0460C8C7708E5623A4FD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6591A89D815345A398EF665551DE0044 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35BDCE8184FC4E22ABA6E5139FA4E156 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-stay-easy'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'Production'
          package: node-app